server/main/urls.py
from django.urls import path

from main.views import index, about, contacts


app_name = 'main'


urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('contacts/', contacts, name='contacts'),
    
]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('products/', include('products.urls.products')),
    path('categories/', include('products.urls.categories'))
]

if settings.DEBUG == True:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

server/main/views.py
from django.shortcuts import render
from django.utils.html import mark_safe
from django.template.loader import get_template, render_to_string
from django.http import HttpResponse


# Create your views here.
def index(request):
    template = get_template('main/index.html')
    context = {
        'description': 'Главная страница Интернет-витрины',
        'page_title': 'Main Page'
    }

    return HttpResponse(template.render(context))
    
def contacts(request):
    return render(
        request,
        'main/contacts.html',
        {
            'page_title': 'Contacts',
            'contacts': ['Contact 1', 'Contact 2', 'Contact 3', 'Contact 4', 'Contact 5']
        }
    )

def about(request):
        return HttpResponse(
            render_to_string(
                'main/about.html',
                {
                    'description': 'Информационная страница Интернет-витрины',
                    'page_title': 'About'
                }
            )
        )

server/main/templates/main/about.html
{% extends 'main/master.html' %}

{% block page_title %}
About page
{% endblock %}

{% block page_content %}
    <div class="branding">
        <img src="" alt="" class="branding__background">
        <span class="branding__snippet">
            {{ description }}
        </span>
    </div>
{% endblock %}

server/main/templates/main/contacts.html
{% extends 'main/master.html' %}

{% block page_title %}
Contacts page
{% endblock %}

{% block page_content %}
    <ul class="contacts-list"></ul>
    {% for item in contacts %}
        <li>
            <span>
                {{ item }}
            </span>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

server/main/templates/main/index.html
{% extends 'main/master.html' %}

{% block page_title %}
Main page
{% endblock %}

{% block page_content %}
    <div class="page__preview">
        <img src="" alt="" class="branding__background">
        <span class="branding__snippet">
            {{ description }}
        </span>
    </div>
{% endblock %}

server/main/templates/main/master.html
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8" />
        <title>{% block page_title %}{% endblock %}</title>
        <link rel="stylesheet" type="text/css" media="screen" href="/static/main/css/index.css" />
    </head>

    <body>
        <div class="page">
            <header class="page__header">
                <nav class="page__navigation">
                    <ul class="navigation-list">
                        <li class="navigation-list__item">
                            <span class="navigation-list__item-text">
                                Главная
                            </span>
                            <a href="{% url 'main:index' %}" class="navigation-list__item-link">
                            </a>
                        </li>
                        <li class="navigation-list__item">
                            <span class="navigation-list__item-text">
                                Продукты
                            </span>
                            <a href="{% url 'products:index' %}" class="navigation-list__item-link">
                            </a>
                        </li>
                        <li class="navigation-list__item">
                            <span class="navigation-list__item-text">
                                Категории
                            </span>
                            <a href="{% url 'categories:index' %}" class="navigation-list__item-link">
                            </a>
                        </li>
                        <li class="navigation-list__item">
                            <span class="navigation-list__item-text">
                                О проекте
                            </span>
                            <a href="{% url 'main:about' %}" class="navigation-list__item-link">
                            </a>
                        </li>
                        <li class="navigation-list__item">
                            <span class="navigation-list__item-text">
                                Контакты
                            </span>
                            <a href="{% url 'main:contacts' %}" class="navigation-list__item-link">
                            </a>
                        </li>
                    </ul>
                </nav>
            </header>
            <div class="page__content">
                <h1 class="page__title">
                    {{ page_title }}
                </h1>
                {% block page_content %}
                {% endblock %}
            </div>
            

            <footer class="page__footer">
                <span class="page__copyright">
                    © GeekBrains
                </span>
            </footer>
        </div>
    </body>
</html>